### ISSUE TITLE
Tags should be scoped to a chain or community

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth-oss#161]
With the addition of a tag controller (#143) the full set of tags is now loaded and visible across all communities. In order to keep tags manageable, we should scope them to a specific community.

* Database can stay intact
* Tags should be loaded on the frontend for the currently selected chain/community
  * There should be a tags route that only selects tags for a specific community
  * Status.ts/app.ts should hit that route, fetching tags only for the specific community at hand
* There may need to be changes in store if it is not clear that the stored tags belong to the current community
* We should make sure that it's not possible to associate a post with a tag on a different chain/community

**Comment by gdjohnson** [comment]
Happy to work on this, though I think I'd need slightly more clarity as to what you have in mind.

**Comment by gdjohnson** [comment]
Surveying this, it's my impression all the desired functionality is already implemented.
1. `app.tags` contains the tags of any community/chain visited in a session, listed under the community/chain name
2. `activeEntity.meta` contains only the tags of the specific chain/community
3. the TagAutocomplete component only suggests tags from `activeEntity.meta`, and the backend uses the active community/chain id in its findOrCreate method

**Comment by raykyri** [comment]
I guess the only thing to change is adding a filter on the manage tags page then?

**Comment by gdjohnson** [comment]
Isn't it already filtered? I can only see the current community's tags.
It is true that the way it's populated is pretty funky right now (pulling from the activeEntity's threads, instead of off `aciveEntity.meta` or `app.tags`) but that was set up because we needed a "count" for each tag (of how many posts reference it). That count isn't store anywhere, so the only way to get it is to loop & tally. We could set up a count in the backend, but with the ability for admins to edit tag names & users to edit/delete thread tags, things could get dicey fast.
